export const MAV_CMD: Record<number, { name: string; short: string }> = {
  16: { name: "NAV_WAYPOINT", short: "Waypoint" },
  17: { name: "NAV_LOITER_UNLIM", short: "Loiter" },
  18: { name: "NAV_LOITER_TURNS", short: "Loiter Turns" },
  19: { name: "NAV_LOITER_TIME", short: "Loiter Time" },
  20: { name: "NAV_RETURN_TO_LAUNCH", short: "RTL" },
  21: { name: "NAV_LAND", short: "Land" },
  22: { name: "NAV_TAKEOFF", short: "Takeoff" },
  23: { name: "NAV_LAND_LOCAL", short: "Land Local" },
  24: { name: "NAV_TAKEOFF_LOCAL", short: "Takeoff Local" },
  25: { name: "NAV_FOLLOW", short: "Follow" },
  30: { name: "NAV_CONTINUE_AND_CHANGE_ALT", short: "Change Alt" },
  31: { name: "NAV_LOITER_TO_ALT", short: "Loiter to Alt" },
  82: { name: "NAV_SPLINE_WAYPOINT", short: "Spline WP" },
  83: { name: "NAV_ALTITUDE_WAIT", short: "Alt Wait" },
  84: { name: "NAV_VTOL_TAKEOFF", short: "VTOL Takeoff" },
  85: { name: "NAV_VTOL_LAND", short: "VTOL Land" },
  92: { name: "NAV_GUIDED_ENABLE", short: "Guided Enable" },
  93: { name: "NAV_DELAY", short: "Delay" },
  94: { name: "NAV_PAYLOAD_PLACE", short: "Payload Place" },
  95: { name: "NAV_LAST", short: "Nav Last" },
  112: { name: "CONDITION_DELAY", short: "Cond Delay" },
  113: { name: "CONDITION_CHANGE_ALT", short: "Cond Change Alt" },
  114: { name: "CONDITION_DISTANCE", short: "Cond Distance" },
  115: { name: "CONDITION_YAW", short: "Cond Yaw" },
  176: { name: "DO_SET_MODE", short: "Set Mode" },
  177: { name: "DO_JUMP", short: "Jump" },
  178: { name: "DO_CHANGE_SPEED", short: "Change Speed" },
  179: { name: "DO_SET_HOME", short: "Set Home" },
  181: { name: "DO_SET_RELAY", short: "Set Relay" },
  182: { name: "DO_REPEAT_RELAY", short: "Repeat Relay" },
  183: { name: "DO_SET_SERVO", short: "Set Servo" },
  184: { name: "DO_REPEAT_SERVO", short: "Repeat Servo" },
  189: { name: "DO_LAND_START", short: "Land Start" },
  190: { name: "DO_RALLY_LAND", short: "Rally Land" },
  191: { name: "DO_GO_AROUND", short: "Go Around" },
  192: { name: "DO_REPOSITION", short: "Reposition" },
  193: { name: "DO_PAUSE_CONTINUE", short: "Pause/Continue" },
  194: { name: "DO_SET_REVERSE", short: "Set Reverse" },
  195: { name: "DO_SET_ROI_LOCATION", short: "ROI Location" },
  196: { name: "DO_SET_ROI_WPNEXT_OFFSET", short: "ROI WP Offset" },
  197: { name: "DO_SET_ROI_NONE", short: "ROI None" },
  200: { name: "DO_CONTROL_VIDEO", short: "Control Video" },
  201: { name: "DO_SET_ROI", short: "Set ROI" },
  203: { name: "DO_DIGICAM_CONTROL", short: "Digicam Ctrl" },
  206: { name: "DO_MOUNT_CONTROL", short: "Mount Ctrl" },
  252: { name: "DO_SET_CAM_TRIGG_DIST", short: "Cam Trig Dist" },
  5001: { name: "NAV_FENCE_RETURN_POINT", short: "Fence Return" },
  5002: { name: "NAV_FENCE_POLYGON_VERTEX_INCLUSION", short: "Fence Incl" },
  5003: { name: "NAV_FENCE_POLYGON_VERTEX_EXCLUSION", short: "Fence Excl" },
  5004: { name: "NAV_FENCE_CIRCLE_INCLUSION", short: "Fence Circle Incl" },
  5005: { name: "NAV_FENCE_CIRCLE_EXCLUSION", short: "Fence Circle Excl" },
  5100: { name: "NAV_RALLY_POINT", short: "Rally Point" },
};

export function commandName(cmd: number): string {
  return MAV_CMD[cmd]?.short ?? `CMD ${cmd}`;
}

export function commandFullName(cmd: number): string {
  return MAV_CMD[cmd]?.name ?? `MAV_CMD_${cmd}`;
}
